/** @type {import('tailwindcss').Config} */
// todo: build files array and look for parent theme config using style.css as the giude. Deep merge the two configs to allow for child theme to override parent theme settings.
// inser the collated styles into a raw format in the file array, { raw:'<div class="$classes_here">', extension: 'html' }

const colors = require('tailwindcss/colors.js');

module.exports = {
    content: {
      relative: true,
      files: [
          "./*.php",
          "./template_parts/**/*.php",
          "./src/**/*.php",
          "./woocommerce/**/*.php", 
          "./templates/**/*.html", 
          "./assets/**/*.js", , 
          "./includes/*.php",
          "./design.json",
        ],
    },
    safelist: [{
      pattern : /^html-post/, // Example for dynamically generated classes
    }],
    theme: {
      extend: {
        screens: {
          'sm': '640px',
          'md': '768px',
          'lg': '1024px',
          'xl': '1280px',
          '2xl': '1536px',
          '3xl': '1800px',
          desktopMax: '2400px',
          '4k': '3840px',
        },
        colors: {
          // system color.  todo: Needs to be refined at some point
          // add more as needed
          current: 'currentColor',
          transparent: 'transparent',
          gray: colors.gray,
          neutral: colors.neutral,
          emerald: colors.emerald,
          indigo: colors.indigo,
          amber: colors.amber,
          red: colors.red,
          rose: colors.rose,

          // simple colors
          white: "var(--white)",
          black: "var(--black)",
          warning: "var(--warning)",
          danger: "var(--danger)",
          light: "var(--light)",
          dark: "var(--dark)",
          success: "var(--success)",
          error: "var(--error)",
          info: "var(--info)",
          body: "var(--body)",
          // complex colors that have inversions
          heading: "var(--heading)",
          "heading-inv": "var(--heading-inv)",
          "heading-link": "var(--heading-link)",
          "heading-link-hover": "var(--heading-link-hover)",
          "link-color": "var(--link-color)",
          "link-color-inv": "var(--link-inv)",
          "link-hover": "var(--link-hover)",
          "link-hover-inv": "var(--link-hover-inv)",
          "link-visited": "var(--link-visited)",
          "link-visited-inv": "var(--link-visited-inv)",
          'surface-background': "var(--surface-background)",
          'surface-background-inv': "var(--surface-background-inv)",
          'surface-text' : "var(--surface-text)",
          'surface-text-inv' : "var(--surface-text-inv)",
          'surface-heading' : "var(--surface-heading)",
          'surface-heading-inv' : "var(--surface-heading-inv)",
          'surface-link' : "var(--surface-link)",
          'surface-link-inv' : "var(--surface-link-inv)",
          'surface-link-hover': "var(--surface-link-hover)",
          'surface-link-hover-inv': "var(--surface-link-hover-inv)",
          'surface-link-visited': "var(--surface-link-visited)",
          'surface-link-visited-inv': "var(--surface-link-visited-inv)",
          // theme default
          "text-body": "var(--text-body)",
          "body-background": "var(--body-background)",
          // theme colors that have all colors and inversions
          primary: {
            50: "var(--primary-50)",
            100: "var(--primary-100)",
            200: "var(--primary-200)",
            300: "var(--primary-300)",
            400: "var(--primary-400)",
            500: "var(--primary-500)",
            600: "var(--primary-600)",
            700: "var(--primary-700)",
            800: "var(--primary-800)",
            900: "var(--primary-900)",
            950: "var(--primary-950)",
          },
          "primary-inv": {
            50: "var(--primary-inv-50)",
            100: "var(--primary-inv-100)",
            200: "var(--primary-inv-200)",
            300: "var(--primary-inv-300)",
            400: "var(--primary-inv-400)",
            500: "var(--primary-inv-500)",
            600: "var(--primary-inv-600)",
            700: "var(--primary-inv-700)",
            800: "var(--primary-inv-800)",
            900: "var(--primary-inv-900)",
            950: "var(--primary-inv-950)",
          },
          secondary: {
            50: "var(--secondary-50)",
            100: "var(--secondary-100)",
            200: "var(--secondary-200)",
            300: "var(--secondary-300)",
            400: "var(--secondary-400)",
            500: "var(--secondary-500)",
            600: "var(--secondary-600)",
            700: "var(--secondary-700)",
            800: "var(--secondary-800)",
            900: "var(--secondary-900)",
            950: "var(--secondary-950)",
          },
          "secondary-inv": {
            50: "var(--secondary-inv-50)",
            100: "var(--secondary-inv-100)",
            200: "var(--secondary-inv-200)",
            300: "var(--secondary-inv-300)",
            400: "var(--secondary-inv-400)",
            500: "var(--secondary-inv-500)",
            600: "var(--secondary-inv-600)",
            700: "var(--secondary-inv-700)",
            800: "var(--secondary-inv-800)",
            900: "var(--secondary-inv-900)",
            950: "var(--secondary-inv-950)",
          },
          tertiary: {
            50: "var(--tertiary-50)",
            100: "var(--tertiary-100)",
            200: "var(--tertiary-200)",
            300: "var(--tertiary-300)",
            400: "var(--tertiary-400)",
            500: "var(--tertiary-500)",
            600: "var(--tertiary-600)",
            700: "var(--tertiary-700)",
            800: "var(--tertiary-800)",
            900: "var(--tertiary-900)",
            950: "var(--tertiary-950)",
          },
          "tertiary-inv": {
            50: "var(--tertiary-inv-50)",
            100: "var(--tertiary-inv-100)",
            200: "var(--tertiary-inv-200)",
            300: "var(--tertiary-inv-300)",
            400: "var(--tertiary-inv-400)",
            500: "var(--tertiary-inv-500)",
            600: "var(--tertiary-inv-600)",
            700: "var(--tertiary-inv-700)",
            800: "var(--tertiary-inv-800)",
            900: "var(--tertiary-inv-900)",
            950: "var(--tertiary-inv-950)",
          },
          cta: {
            50: "var(--cta-50)",
            100: "var(--cta-100)",
            200: "var(--cta-200)",
            300: "var(--cta-300)",
            400: "var(--cta-400)",
            500: "var(--cta-500)",
            600: "var(--cta-600)",
            700: "var(--cta-700)",
            800: "var(--cta-800)",
            900: "var(--cta-900)",
            950: "var(--cta-950)",
          },
          "cta-inv": {
            50: "var(--cta-inv-50)",
            100: "var(--cta-inv-100)",
            200: "var(--cta-inv-200)",
            300: "var(--cta-inv-300)",
            400: "var(--cta-inv-400)",
            500: "var(--cta-inv-500)",
            600: "var(--cta-inv-600)",
            700: "var(--cta-inv-700)",
            800: "var(--cta-inv-800)",
            900: "var(--cta-inv-900)",
            950: "var(--cta-inv-950)",
          },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
  }
}

